### ISSUE TITLE
problem with pyTenable sc.feeds.process() function

### ISSUE THREAD

**Issue by rs904c** [tenable/pyTenable#201]
There seems to be a problem with the pyTenable sc.feeds.process() function.
I'm trying to update a feed with a file I have locally.
Here is my debug, when I was doing a sc.feeds.process():
DEBUG:tenable.sc.TenableSC:{"method": "POST", "url": "https://192.168.214.5:443/rest/file/upload", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:Resetting dropped connection: 192.168.214.5
DEBUG:urllib3.connectionpool:https://192.168.214.5:443 "POST /rest/file/upload HTTP/1.1" 200 194
DEBUG:tenable.sc.TenableSC:{"method": "POST", "url": "https://192.168.214.5:443/rest/feed/sc/update", "params": {}, "body": {"filename": "zIwqQT"}} 
 
sc.feeds.process() was incorrectly doing a update, when it should instead do a feed/sc/process

**Comment by rs904c** [comment]
Even though the above returns a 200 code, it always fails.

The SC system logs show the following:
Job id #760 terminated abnormally with error status '60'. (command: /opt/sc/support/bin/php /opt/sc/src/tools/feedUpdate.php 760; initiator = 2; object = no_object; jobparams = a:1:{s:4:"type";s:2:"sc";}; pid: 16701)

**Comment by SteveMcGrath** [comment]
This issue should be resolved now.  This was originally missed as the test had to be skipped because of the size of the plugin downloads.  Not a great answer, but the current testing suite would have lead to some massive mocked yaml files in the code repo if it wasn't skipped.

**Comment by rs904c** [comment]
I upgraded my pyTenable however, I'm still seeing this problem.  I'm seeing an update instead of process.   Steve, Can you double check this on your end?

DEBUG:tenable.sc.TenableSC:{"method": "POST", "url": "https://192.168.214.5:443/rest/file/upload", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:https://192.168.214.5:443 "POST /rest/file/upload HTTP/1.1" 200 194
DEBUG:tenable.sc.TenableSC:{"method": "POST", "url": "https://192.168.214.5:443/rest/file/upload", "params": {}, "body": {}}
DEBUG:urllib3.connectionpool:https://192.168.214.5:443 "POST /rest/file/upload HTTP/1.1" 200 194
DEBUG:tenable.sc.TenableSC:{"method": "POST", "url": "https://192.168.214.5:443/rest/feed/sc/update", "params": {}, "body": {"filename": "Rlpwab"}}
DEBUG:urllib3.connectionpool:https://192.168.214.5:443 "POST /rest/feed/sc/update HTTP/1.1" 200 100

**Comment by SteveMcGrath** [comment]
1.1.2 has yet to be released.  If you want bleeding edge, then you may want to pull directly from github.
